import type { SolarComponent, SolarPackage } from '../../domain/packages/types';

export const component = (
  overrides: Partial<SolarComponent>,
): SolarComponent => ({
  id: 'c',
  name: 'Component',
  brand: 'Brand',
  model: 'Model',
  category: 'Inverter',
  unitPrice: 1000,
  pricingEnabled: true,
  productionCapacityKwp: 0,
  loadCapacityKw: 0,
  storageCapacityKwh: 0,
  parallelMax: 1,
  pvMinPower: null,
  pvMaxPower: null,
  batteryMaxCapacity: null,
  dataSheetUrl: null,
  ...overrides,
});

export const hybridPackage = (
  overrides: Partial<SolarPackage> = {},
  inverterBrand = 'Sofar',
): SolarPackage => ({
  id: 'pkg-1',
  name: '6kW Hybrid',
  solarKwp: 6.3,
  inverterKw: 6,
  storageKwh: 5,
  phase: 'single',
  totalPrice: 300000,
  billRangeMin: 5000,
  billRangeMax: 8000,
  isActive: true,
  isRecommended: false,
  sortOrder: 1,
  ipRating: null,
  imageUrl: null,
  mainFeatures: [],
  createdAt: '2026-01-01T00:00:00.000Z',
  components: [
    {
      componentId: 'inv',
      quantity: 1,
      baseComponentId: null,
      multiplier: null,
      component: component({
        id: 'inv',
        brand: inverterBrand,
        model: 'HYD 6K',
        category: 'Inverter',
        loadCapacityKw: 6,
        parallelMax: 3,
        pvMinPower: 2,
        pvMaxPower: 9,
        batteryMaxCapacity: 20,
        unitPrice: 100000,
      }),
    },
    {
      componentId: 'bat',
      quantity: 1,
      baseComponentId: null,
      multiplier: null,
      component: component({
        id: 'bat',
        brand: 'Pylon',
        model: 'US5000',
        category: 'Battery',
        storageCapacityKwh: 5,
        unitPrice: 80000,
      }),
    },
    {
      componentId: 'pan',
      quantity: 14,
      baseComponentId: null,
      multiplier: null,
      component: component({
        id: 'pan',
        brand: 'Jinko',
        model: '450W',
        category: 'Solar Panel',
        productionCapacityKwp: 0.45,
        unitPrice: 5000,
      }),
    },
    {
      componentId: 'rail',
      quantity: 7,
      baseComponentId: 'pan',
      multiplier: 0.5,
      component: component({
        id: 'rail',
        brand: 'K2',
        name: 'Rail',
        model: 'R1',
        category: 'Mounting & Racking',
        unitPrice: 500,
      }),
    },
  ],
  ...overrides,
});
